configure micro-airport-location in Kubernetes
cichan02/airport-infrastructure pull request #4
Opened 2023-04-19 09:05 UTC by cichan02

## PR-Codex overview
This PR adds Kubernetes deployment and service configurations for Redis and MongoDB, and a load balancer for the airport location service.

### Detailed summary
- Added Kubernetes ConfigMaps for Redis and MongoDB
- Added Kubernetes Secrets for MongoDB authentication
- Added Kubernetes Services for Redis, MongoDB, and airport location
- Added Kubernetes Deployments for Redis, MongoDB, and airport location
- Added Kubernetes StatefulSet for MongoDB with persistent volume claims

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2023-04-20 11:49 UTC, h1alexbel requested changes

2023-04-20 11:49 UTC, h1alexbel commented on micro-airport-location/redis-deployment.yml
> +          imagePullPolicy: IfNotPresent
@cichan02 should be `Always`
we expect our pod to be crashed each time the container not found in the registry

2023-04-20 11:49 UTC, h1alexbel commented on micro-airport-location/mongo-statefulset.yml
> +          imagePullPolicy: IfNotPresent
@cichan02 should be Always
we expect our pod to be crashed each time the container is not found in the registry

2023-04-20 15:06 UTC, cichan02 commented
Injected Semantic Versioning

2023-04-21 12:09 UTC, h1alexbel approved these changes

2023-04-21 12:10 UTC, h1alexbel commented
@cichan02 nice, *ensure*

2023-04-21 12:10 UTC, merged