configure micro-airport-core in Kubernetes
cichan02/airport-infrastructure pull request #5
Opened 2023-04-19 11:10 UTC by cichan02

2023-04-20 12:06 UTC, h1alexbel requested changes

2023-04-20 12:06 UTC, h1alexbel commented on micro-airport-core/airport-core-deployment.yml
> +          image: cichan/micro-airport-core:prod
use https://semver.org/

2023-04-20 15:05 UTC, cichan02 commented on micro-airport-core/airport-core-deployment.yml
> +          image: cichan/micro-airport-core:prod
injected Semantic Versioning

2023-04-21 12:10 UTC, h1alexbel approved these changes

2023-04-21 12:10 UTC, merged